uint8 workMode
string curPathName
int16 percent
uint8 searchPathNum
string searchPathName

int32 actionCode
int32 actionValue
uint8 taskExecuStatus
uint8 bypassRequest
uint8 bypassProcessing #0 no 1 yes
#all msg
uint8[] faultCode
#nav msg
float32 curXAxis
float32 curYAxis
float32 curHead
float32 curSpeed
#vehicle msg
uint8 curGear
uint8 hookState
int16 wheelAngle
uint8 emergencyStop
uint8 batteryPower
