// Generated by gencpp from file canbus/can_msg.msg
// DO NOT EDIT!


#ifndef CANBUS_MESSAGE_CAN_MSG_H
#define CANBUS_MESSAGE_CAN_MSG_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace canbus
{
template <class ContainerAllocator>
struct can_msg_
{
  typedef can_msg_<ContainerAllocator> Type;

  can_msg_()
    : throttlePercent(0)
    , brakePercent(0)
    , wheelAngle(0)
    , vehicleSpeed(0.0)
    , curGear(0)
    , hookState(0)
    , linkPallet(0)
    , controlPanelState(0)
    , eabPanelState(0)
    , emergencyStop(0)
    , batteryPower(0)
    , hookButton(0)
    , linkButton(0)
    , faultCode()
    , epsCMD(0)
    , wheelAngleCMD(0.0)
    , epsMode(0)
    , epsCurrent(0.0)
    , epsCentring(0)
    , epsERR1(0)
    , epsERR2(0)
    , rawcommand()
    , rawfeedback()  {
    }
  can_msg_(const ContainerAllocator& _alloc)
    : throttlePercent(0)
    , brakePercent(0)
    , wheelAngle(0)
    , vehicleSpeed(0.0)
    , curGear(0)
    , hookState(0)
    , linkPallet(0)
    , controlPanelState(0)
    , eabPanelState(0)
    , emergencyStop(0)
    , batteryPower(0)
    , hookButton(0)
    , linkButton(0)
    , faultCode(_alloc)
    , epsCMD(0)
    , wheelAngleCMD(0.0)
    , epsMode(0)
    , epsCurrent(0.0)
    , epsCentring(0)
    , epsERR1(0)
    , epsERR2(0)
    , rawcommand(_alloc)
    , rawfeedback(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _throttlePercent_type;
  _throttlePercent_type throttlePercent;

   typedef uint8_t _brakePercent_type;
  _brakePercent_type brakePercent;

   typedef int16_t _wheelAngle_type;
  _wheelAngle_type wheelAngle;

   typedef float _vehicleSpeed_type;
  _vehicleSpeed_type vehicleSpeed;

   typedef uint8_t _curGear_type;
  _curGear_type curGear;

   typedef uint8_t _hookState_type;
  _hookState_type hookState;

   typedef uint8_t _linkPallet_type;
  _linkPallet_type linkPallet;

   typedef uint8_t _controlPanelState_type;
  _controlPanelState_type controlPanelState;

   typedef uint8_t _eabPanelState_type;
  _eabPanelState_type eabPanelState;

   typedef uint8_t _emergencyStop_type;
  _emergencyStop_type emergencyStop;

   typedef uint8_t _batteryPower_type;
  _batteryPower_type batteryPower;

   typedef uint8_t _hookButton_type;
  _hookButton_type hookButton;

   typedef uint8_t _linkButton_type;
  _linkButton_type linkButton;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _faultCode_type;
  _faultCode_type faultCode;

   typedef uint8_t _epsCMD_type;
  _epsCMD_type epsCMD;

   typedef float _wheelAngleCMD_type;
  _wheelAngleCMD_type wheelAngleCMD;

   typedef uint8_t _epsMode_type;
  _epsMode_type epsMode;

   typedef float _epsCurrent_type;
  _epsCurrent_type epsCurrent;

   typedef uint8_t _epsCentring_type;
  _epsCentring_type epsCentring;

   typedef uint8_t _epsERR1_type;
  _epsERR1_type epsERR1;

   typedef uint8_t _epsERR2_type;
  _epsERR2_type epsERR2;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _rawcommand_type;
  _rawcommand_type rawcommand;

   typedef std::vector<uint8_t, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<uint8_t>> _rawfeedback_type;
  _rawfeedback_type rawfeedback;





  typedef boost::shared_ptr< ::canbus::can_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::canbus::can_msg_<ContainerAllocator> const> ConstPtr;

}; // struct can_msg_

typedef ::canbus::can_msg_<std::allocator<void> > can_msg;

typedef boost::shared_ptr< ::canbus::can_msg > can_msgPtr;
typedef boost::shared_ptr< ::canbus::can_msg const> can_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::canbus::can_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::canbus::can_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::canbus::can_msg_<ContainerAllocator1> & lhs, const ::canbus::can_msg_<ContainerAllocator2> & rhs)
{
  return lhs.throttlePercent == rhs.throttlePercent &&
    lhs.brakePercent == rhs.brakePercent &&
    lhs.wheelAngle == rhs.wheelAngle &&
    lhs.vehicleSpeed == rhs.vehicleSpeed &&
    lhs.curGear == rhs.curGear &&
    lhs.hookState == rhs.hookState &&
    lhs.linkPallet == rhs.linkPallet &&
    lhs.controlPanelState == rhs.controlPanelState &&
    lhs.eabPanelState == rhs.eabPanelState &&
    lhs.emergencyStop == rhs.emergencyStop &&
    lhs.batteryPower == rhs.batteryPower &&
    lhs.hookButton == rhs.hookButton &&
    lhs.linkButton == rhs.linkButton &&
    lhs.faultCode == rhs.faultCode &&
    lhs.epsCMD == rhs.epsCMD &&
    lhs.wheelAngleCMD == rhs.wheelAngleCMD &&
    lhs.epsMode == rhs.epsMode &&
    lhs.epsCurrent == rhs.epsCurrent &&
    lhs.epsCentring == rhs.epsCentring &&
    lhs.epsERR1 == rhs.epsERR1 &&
    lhs.epsERR2 == rhs.epsERR2 &&
    lhs.rawcommand == rhs.rawcommand &&
    lhs.rawfeedback == rhs.rawfeedback;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::canbus::can_msg_<ContainerAllocator1> & lhs, const ::canbus::can_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace canbus

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::canbus::can_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::canbus::can_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canbus::can_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::canbus::can_msg_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canbus::can_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::canbus::can_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::canbus::can_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f00c5ecbfa019694969397666d50d173";
  }

  static const char* value(const ::canbus::can_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf00c5ecbfa019694ULL;
  static const uint64_t static_value2 = 0x969397666d50d173ULL;
};

template<class ContainerAllocator>
struct DataType< ::canbus::can_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "canbus/can_msg";
  }

  static const char* value(const ::canbus::can_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::canbus::can_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 throttlePercent\n"
"uint8 brakePercent\n"
"int16 wheelAngle\n"
"float32 vehicleSpeed #  m/s\n"
"\n"
"uint8 curGear\n"
"#0 no 1 yes\n"
"uint8 hookState\n"
"uint8 linkPallet\n"
"uint8 controlPanelState\n"
"uint8 eabPanelState\n"
"uint8 emergencyStop\n"
"uint8 batteryPower\n"
"uint8 hookButton\n"
"uint8 linkButton\n"
"\n"
"#uint8[] ultrasoundDis\n"
"#uint8[] timState\n"
"#uint8 safeTouch\n"
"\n"
"uint8[] faultCode\n"
"\n"
"\n"
"#new eps msg zhangyu 20220226\n"
"uint8 epsCMD\n"
"float32 wheelAngleCMD\n"
"uint8 epsMode\n"
"float32 epsCurrent\n"
"uint8 epsCentring\n"
"uint8 epsERR1\n"
"uint8 epsERR2\n"
"\n"
"uint8[] rawcommand\n"
"uint8[] rawfeedback\n"
"\n"
;
  }

  static const char* value(const ::canbus::can_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::canbus::can_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.throttlePercent);
      stream.next(m.brakePercent);
      stream.next(m.wheelAngle);
      stream.next(m.vehicleSpeed);
      stream.next(m.curGear);
      stream.next(m.hookState);
      stream.next(m.linkPallet);
      stream.next(m.controlPanelState);
      stream.next(m.eabPanelState);
      stream.next(m.emergencyStop);
      stream.next(m.batteryPower);
      stream.next(m.hookButton);
      stream.next(m.linkButton);
      stream.next(m.faultCode);
      stream.next(m.epsCMD);
      stream.next(m.wheelAngleCMD);
      stream.next(m.epsMode);
      stream.next(m.epsCurrent);
      stream.next(m.epsCentring);
      stream.next(m.epsERR1);
      stream.next(m.epsERR2);
      stream.next(m.rawcommand);
      stream.next(m.rawfeedback);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct can_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::canbus::can_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::canbus::can_msg_<ContainerAllocator>& v)
  {
    s << indent << "throttlePercent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.throttlePercent);
    s << indent << "brakePercent: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.brakePercent);
    s << indent << "wheelAngle: ";
    Printer<int16_t>::stream(s, indent + "  ", v.wheelAngle);
    s << indent << "vehicleSpeed: ";
    Printer<float>::stream(s, indent + "  ", v.vehicleSpeed);
    s << indent << "curGear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.curGear);
    s << indent << "hookState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hookState);
    s << indent << "linkPallet: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.linkPallet);
    s << indent << "controlPanelState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.controlPanelState);
    s << indent << "eabPanelState: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.eabPanelState);
    s << indent << "emergencyStop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.emergencyStop);
    s << indent << "batteryPower: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.batteryPower);
    s << indent << "hookButton: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.hookButton);
    s << indent << "linkButton: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.linkButton);
    s << indent << "faultCode[]" << std::endl;
    for (size_t i = 0; i < v.faultCode.size(); ++i)
    {
      s << indent << "  faultCode[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.faultCode[i]);
    }
    s << indent << "epsCMD: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.epsCMD);
    s << indent << "wheelAngleCMD: ";
    Printer<float>::stream(s, indent + "  ", v.wheelAngleCMD);
    s << indent << "epsMode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.epsMode);
    s << indent << "epsCurrent: ";
    Printer<float>::stream(s, indent + "  ", v.epsCurrent);
    s << indent << "epsCentring: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.epsCentring);
    s << indent << "epsERR1: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.epsERR1);
    s << indent << "epsERR2: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.epsERR2);
    s << indent << "rawcommand[]" << std::endl;
    for (size_t i = 0; i < v.rawcommand.size(); ++i)
    {
      s << indent << "  rawcommand[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.rawcommand[i]);
    }
    s << indent << "rawfeedback[]" << std::endl;
    for (size_t i = 0; i < v.rawfeedback.size(); ++i)
    {
      s << indent << "  rawfeedback[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.rawfeedback[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // CANBUS_MESSAGE_CAN_MSG_H
