// Generated by gencpp from file ivlocmsg/ivsensorimu.msg
// DO NOT EDIT!


#ifndef IVLOCMSG_MESSAGE_IVSENSORIMU_H
#define IVLOCMSG_MESSAGE_IVSENSORIMU_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ivlocmsg
{
template <class ContainerAllocator>
struct ivsensorimu_
{
  typedef ivsensorimu_<ContainerAllocator> Type;

  ivsensorimu_()
    : header()
    , update(false)
    , TimeTag(0)
    , utcTime(0.0)
    , gyro_x(0.0)
    , gyro_y(0.0)
    , gyro_z(0.0)
    , acce_x(0.0)
    , acce_y(0.0)
    , acce_z(0.0)
    , Temperature(0.0)  {
    }
  ivsensorimu_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , update(false)
    , TimeTag(0)
    , utcTime(0.0)
    , gyro_x(0.0)
    , gyro_y(0.0)
    , gyro_z(0.0)
    , acce_x(0.0)
    , acce_y(0.0)
    , acce_z(0.0)
    , Temperature(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _update_type;
  _update_type update;

   typedef uint32_t _TimeTag_type;
  _TimeTag_type TimeTag;

   typedef double _utcTime_type;
  _utcTime_type utcTime;

   typedef double _gyro_x_type;
  _gyro_x_type gyro_x;

   typedef double _gyro_y_type;
  _gyro_y_type gyro_y;

   typedef double _gyro_z_type;
  _gyro_z_type gyro_z;

   typedef double _acce_x_type;
  _acce_x_type acce_x;

   typedef double _acce_y_type;
  _acce_y_type acce_y;

   typedef double _acce_z_type;
  _acce_z_type acce_z;

   typedef double _Temperature_type;
  _Temperature_type Temperature;





  typedef boost::shared_ptr< ::ivlocmsg::ivsensorimu_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ivlocmsg::ivsensorimu_<ContainerAllocator> const> ConstPtr;

}; // struct ivsensorimu_

typedef ::ivlocmsg::ivsensorimu_<std::allocator<void> > ivsensorimu;

typedef boost::shared_ptr< ::ivlocmsg::ivsensorimu > ivsensorimuPtr;
typedef boost::shared_ptr< ::ivlocmsg::ivsensorimu const> ivsensorimuConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ivlocmsg::ivsensorimu_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ivlocmsg::ivsensorimu_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ivlocmsg::ivsensorimu_<ContainerAllocator1> & lhs, const ::ivlocmsg::ivsensorimu_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.update == rhs.update &&
    lhs.TimeTag == rhs.TimeTag &&
    lhs.utcTime == rhs.utcTime &&
    lhs.gyro_x == rhs.gyro_x &&
    lhs.gyro_y == rhs.gyro_y &&
    lhs.gyro_z == rhs.gyro_z &&
    lhs.acce_x == rhs.acce_x &&
    lhs.acce_y == rhs.acce_y &&
    lhs.acce_z == rhs.acce_z &&
    lhs.Temperature == rhs.Temperature;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ivlocmsg::ivsensorimu_<ContainerAllocator1> & lhs, const ::ivlocmsg::ivsensorimu_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ivlocmsg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ivlocmsg::ivsensorimu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ivlocmsg::ivsensorimu_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivlocmsg::ivsensorimu_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivlocmsg::ivsensorimu_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivlocmsg::ivsensorimu_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivlocmsg::ivsensorimu_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ivlocmsg::ivsensorimu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "697c97af3ca632a06ae871001205e47c";
  }

  static const char* value(const ::ivlocmsg::ivsensorimu_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x697c97af3ca632a0ULL;
  static const uint64_t static_value2 = 0x6ae871001205e47cULL;
};

template<class ContainerAllocator>
struct DataType< ::ivlocmsg::ivsensorimu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ivlocmsg/ivsensorimu";
  }

  static const char* value(const ::ivlocmsg::ivsensorimu_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ivlocmsg::ivsensorimu_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool update\n"
"uint32 TimeTag\n"
"float64 utcTime\n"
"float64 gyro_x\n"
"float64 gyro_y\n"
"float64 gyro_z\n"
"float64 acce_x\n"
"float64 acce_y\n"
"float64 acce_z\n"
"float64 Temperature\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ivlocmsg::ivsensorimu_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ivlocmsg::ivsensorimu_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.update);
      stream.next(m.TimeTag);
      stream.next(m.utcTime);
      stream.next(m.gyro_x);
      stream.next(m.gyro_y);
      stream.next(m.gyro_z);
      stream.next(m.acce_x);
      stream.next(m.acce_y);
      stream.next(m.acce_z);
      stream.next(m.Temperature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ivsensorimu_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ivlocmsg::ivsensorimu_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ivlocmsg::ivsensorimu_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "update: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update);
    s << indent << "TimeTag: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.TimeTag);
    s << indent << "utcTime: ";
    Printer<double>::stream(s, indent + "  ", v.utcTime);
    s << indent << "gyro_x: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_x);
    s << indent << "gyro_y: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_y);
    s << indent << "gyro_z: ";
    Printer<double>::stream(s, indent + "  ", v.gyro_z);
    s << indent << "acce_x: ";
    Printer<double>::stream(s, indent + "  ", v.acce_x);
    s << indent << "acce_y: ";
    Printer<double>::stream(s, indent + "  ", v.acce_y);
    s << indent << "acce_z: ";
    Printer<double>::stream(s, indent + "  ", v.acce_z);
    s << indent << "Temperature: ";
    Printer<double>::stream(s, indent + "  ", v.Temperature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IVLOCMSG_MESSAGE_IVSENSORIMU_H
