// Generated by gencpp from file ivlocmsg/ivsensorodom.msg
// DO NOT EDIT!


#ifndef IVLOCMSG_MESSAGE_IVSENSORODOM_H
#define IVLOCMSG_MESSAGE_IVSENSORODOM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ivlocmsg
{
template <class ContainerAllocator>
struct ivsensorodom_
{
  typedef ivsensorodom_<ContainerAllocator> Type;

  ivsensorodom_()
    : header()
    , dFrameCnt(0)
    , velocity_rl(0.0)
    , velocity_rr(0.0)
    , velocity(0.0)  {
    }
  ivsensorodom_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dFrameCnt(0)
    , velocity_rl(0.0)
    , velocity_rr(0.0)
    , velocity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _dFrameCnt_type;
  _dFrameCnt_type dFrameCnt;

   typedef double _velocity_rl_type;
  _velocity_rl_type velocity_rl;

   typedef double _velocity_rr_type;
  _velocity_rr_type velocity_rr;

   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::ivlocmsg::ivsensorodom_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ivlocmsg::ivsensorodom_<ContainerAllocator> const> ConstPtr;

}; // struct ivsensorodom_

typedef ::ivlocmsg::ivsensorodom_<std::allocator<void> > ivsensorodom;

typedef boost::shared_ptr< ::ivlocmsg::ivsensorodom > ivsensorodomPtr;
typedef boost::shared_ptr< ::ivlocmsg::ivsensorodom const> ivsensorodomConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ivlocmsg::ivsensorodom_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ivlocmsg::ivsensorodom_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ivlocmsg::ivsensorodom_<ContainerAllocator1> & lhs, const ::ivlocmsg::ivsensorodom_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.dFrameCnt == rhs.dFrameCnt &&
    lhs.velocity_rl == rhs.velocity_rl &&
    lhs.velocity_rr == rhs.velocity_rr &&
    lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ivlocmsg::ivsensorodom_<ContainerAllocator1> & lhs, const ::ivlocmsg::ivsensorodom_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ivlocmsg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ivlocmsg::ivsensorodom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ivlocmsg::ivsensorodom_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivlocmsg::ivsensorodom_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivlocmsg::ivsensorodom_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivlocmsg::ivsensorodom_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivlocmsg::ivsensorodom_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ivlocmsg::ivsensorodom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "401253d8396a3f09cad05441e6c9bbcc";
  }

  static const char* value(const ::ivlocmsg::ivsensorodom_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x401253d8396a3f09ULL;
  static const uint64_t static_value2 = 0xcad05441e6c9bbccULL;
};

template<class ContainerAllocator>
struct DataType< ::ivlocmsg::ivsensorodom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ivlocmsg/ivsensorodom";
  }

  static const char* value(const ::ivlocmsg::ivsensorodom_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ivlocmsg::ivsensorodom_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"uint8 dFrameCnt	\n"
"float64 velocity_rl\n"
"float64 velocity_rr\n"
"float64 velocity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ivlocmsg::ivsensorodom_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ivlocmsg::ivsensorodom_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dFrameCnt);
      stream.next(m.velocity_rl);
      stream.next(m.velocity_rr);
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ivsensorodom_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ivlocmsg::ivsensorodom_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ivlocmsg::ivsensorodom_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dFrameCnt: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.dFrameCnt);
    s << indent << "velocity_rl: ";
    Printer<double>::stream(s, indent + "  ", v.velocity_rl);
    s << indent << "velocity_rr: ";
    Printer<double>::stream(s, indent + "  ", v.velocity_rr);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IVLOCMSG_MESSAGE_IVSENSORODOM_H
