// Generated by gencpp from file ivlocmsg/ivsensorgps.msg
// DO NOT EDIT!


#ifndef IVLOCMSG_MESSAGE_IVSENSORGPS_H
#define IVLOCMSG_MESSAGE_IVSENSORGPS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ivlocmsg
{
template <class ContainerAllocator>
struct ivsensorgps_
{
  typedef ivsensorgps_<ContainerAllocator> Type;

  ivsensorgps_()
    : header()
    , update(false)
    , lon(0.0)
    , lat(0.0)
    , height(0.0)
    , heading(0.0)
    , velocity(0.0)
    , track_angle(0.0)
    , utctime(0.0)
    , hdop(0.0)
    , diff_age(0.0)
    , base_length(0.0)
    , heading_std(0.0)
    , status(0)
    , satenum(0)
    , status_yaw(0)
    , is_heading_valid(0)  {
    }
  ivsensorgps_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , update(false)
    , lon(0.0)
    , lat(0.0)
    , height(0.0)
    , heading(0.0)
    , velocity(0.0)
    , track_angle(0.0)
    , utctime(0.0)
    , hdop(0.0)
    , diff_age(0.0)
    , base_length(0.0)
    , heading_std(0.0)
    , status(0)
    , satenum(0)
    , status_yaw(0)
    , is_heading_valid(0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _update_type;
  _update_type update;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _height_type;
  _height_type height;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _track_angle_type;
  _track_angle_type track_angle;

   typedef double _utctime_type;
  _utctime_type utctime;

   typedef double _hdop_type;
  _hdop_type hdop;

   typedef double _diff_age_type;
  _diff_age_type diff_age;

   typedef double _base_length_type;
  _base_length_type base_length;

   typedef double _heading_std_type;
  _heading_std_type heading_std;

   typedef uint8_t _status_type;
  _status_type status;

   typedef uint8_t _satenum_type;
  _satenum_type satenum;

   typedef uint8_t _status_yaw_type;
  _status_yaw_type status_yaw;

   typedef uint8_t _is_heading_valid_type;
  _is_heading_valid_type is_heading_valid;





  typedef boost::shared_ptr< ::ivlocmsg::ivsensorgps_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ivlocmsg::ivsensorgps_<ContainerAllocator> const> ConstPtr;

}; // struct ivsensorgps_

typedef ::ivlocmsg::ivsensorgps_<std::allocator<void> > ivsensorgps;

typedef boost::shared_ptr< ::ivlocmsg::ivsensorgps > ivsensorgpsPtr;
typedef boost::shared_ptr< ::ivlocmsg::ivsensorgps const> ivsensorgpsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ivlocmsg::ivsensorgps_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ivlocmsg::ivsensorgps_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ivlocmsg::ivsensorgps_<ContainerAllocator1> & lhs, const ::ivlocmsg::ivsensorgps_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.update == rhs.update &&
    lhs.lon == rhs.lon &&
    lhs.lat == rhs.lat &&
    lhs.height == rhs.height &&
    lhs.heading == rhs.heading &&
    lhs.velocity == rhs.velocity &&
    lhs.track_angle == rhs.track_angle &&
    lhs.utctime == rhs.utctime &&
    lhs.hdop == rhs.hdop &&
    lhs.diff_age == rhs.diff_age &&
    lhs.base_length == rhs.base_length &&
    lhs.heading_std == rhs.heading_std &&
    lhs.status == rhs.status &&
    lhs.satenum == rhs.satenum &&
    lhs.status_yaw == rhs.status_yaw &&
    lhs.is_heading_valid == rhs.is_heading_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ivlocmsg::ivsensorgps_<ContainerAllocator1> & lhs, const ::ivlocmsg::ivsensorgps_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ivlocmsg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ivlocmsg::ivsensorgps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ivlocmsg::ivsensorgps_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivlocmsg::ivsensorgps_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivlocmsg::ivsensorgps_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivlocmsg::ivsensorgps_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivlocmsg::ivsensorgps_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ivlocmsg::ivsensorgps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a648f6943f338c8bbccf86eb538d82e3";
  }

  static const char* value(const ::ivlocmsg::ivsensorgps_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa648f6943f338c8bULL;
  static const uint64_t static_value2 = 0xbccf86eb538d82e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::ivlocmsg::ivsensorgps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ivlocmsg/ivsensorgps";
  }

  static const char* value(const ::ivlocmsg::ivsensorgps_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ivlocmsg::ivsensorgps_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"bool update\n"
"float64 lon\n"
"float64 lat\n"
"float64 height\n"
"float64 heading\n"
"float64 velocity\n"
"float64 track_angle\n"
"float64 utctime	\n"
"float64 hdop\n"
"float64 diff_age\n"
"float64 base_length\n"
"float64 heading_std\n"
"uint8 status\n"
"uint8 satenum\n"
"uint8 status_yaw\n"
"uint8 is_heading_valid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ivlocmsg::ivsensorgps_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ivlocmsg::ivsensorgps_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.update);
      stream.next(m.lon);
      stream.next(m.lat);
      stream.next(m.height);
      stream.next(m.heading);
      stream.next(m.velocity);
      stream.next(m.track_angle);
      stream.next(m.utctime);
      stream.next(m.hdop);
      stream.next(m.diff_age);
      stream.next(m.base_length);
      stream.next(m.heading_std);
      stream.next(m.status);
      stream.next(m.satenum);
      stream.next(m.status_yaw);
      stream.next(m.is_heading_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ivsensorgps_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ivlocmsg::ivsensorgps_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ivlocmsg::ivsensorgps_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "update: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.update);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "track_angle: ";
    Printer<double>::stream(s, indent + "  ", v.track_angle);
    s << indent << "utctime: ";
    Printer<double>::stream(s, indent + "  ", v.utctime);
    s << indent << "hdop: ";
    Printer<double>::stream(s, indent + "  ", v.hdop);
    s << indent << "diff_age: ";
    Printer<double>::stream(s, indent + "  ", v.diff_age);
    s << indent << "base_length: ";
    Printer<double>::stream(s, indent + "  ", v.base_length);
    s << indent << "heading_std: ";
    Printer<double>::stream(s, indent + "  ", v.heading_std);
    s << indent << "status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status);
    s << indent << "satenum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.satenum);
    s << indent << "status_yaw: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.status_yaw);
    s << indent << "is_heading_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_heading_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IVLOCMSG_MESSAGE_IVSENSORGPS_H
