#ifndef __LINUX_GEAC_V4L2_H
#define __LINUX_GEAC_V4L2_H

#define HW_FORMAT_YUV422_8BIT	0x1Eu
#define HW_FORMAT_YUV422_10BIT	0x1Fu
#define HW_FORMAT_RAW8		0x2Au
#define HW_FORMAT_RAW10 	0x2Bu
#define HW_FORMAT_RAW12 	0x2Cu
#define HW_FORMAT_RAW14 	0x2Du
#define HW_FORMAT_RAW16 	0x2Eu
#define HW_FORMAT_RAW20 	0x2Fu


#define V4L2_CTRL_CLASS_CAMERA		0x009a0000	/* Camera class controls */
#define TEGRA_CAMERA_CID_BASE		(V4L2_CTRL_CLASS_CAMERA | 0x2000)

#define RB_CAM_CID_SENSOR_FRMFMT_WIDTH (TEGRA_CAMERA_CID_BASE + 200)  /* Camera width */
#define RB_CAM_CID_SENSOR_FRMFMT_HEIGHT (TEGRA_CAMERA_CID_BASE + 201) /* Camera height */
#define RB_CAM_CID_SENSOR_SFRMFMT_FRAMERATES (TEGRA_CAMERA_CID_BASE + 202) /* fps */
#define RB_CAM_CID_SENSOR_PIXEL_CLOCK (TEGRA_CAMERA_CID_BASE + 220) /* frame_length*line_length*/
#define RB_CAM_CID_SENSOR_SERDES_PIXEL_CLOCK (TEGRA_CAMERA_CID_BASE + 221) /*serdes output clock */
#define RB_CAM_CID_SENSOR_MIPI_CLOCK (TEGRA_CAMERA_CID_BASE + 222) /* Camera mipiclk 数据要为DES速率的1/2 */
#define RB_CAM_CID_IMAGE_LINE_LENGTH (TEGRA_CAMERA_CID_BASE + 240) /* Camera line length */
#define RB_CAM_CID_IAMGE_PIXEL_FORMAT (TEGRA_CAMERA_CID_BASE + 241) /* Camera datatype */
#define RB_CAM_CID_IAMGE_EMBEDDED_METADATA (TEGRA_CAMERA_CID_BASE + 242)


#endif
