<?xml version="1.0"?>
<package format="2">
  <name>hdmap</name>
  <version>1.0.0</version>
  <description>C++11 HD map server SDK with trajectory processing and obstacle lane occupancy for PNC.</description>
  <maintainer email="lizhao@todo.todo">lizhao</maintainer>
  <license>TODO</license>
  <buildtool_depend>catkin</buildtool_depend>
  <build_depend>boost</build_depend>
  <export/>
</package>
