float32 desireSpeed
float32 desireAcc
uint8 throttlePercent   #油门
uint8 brakePercent      #刹车
float32 wheelAngle      #车轮转角

uint8 desireGear
#sound and light
uint8 leftLightEnable   #左灯
uint8 rightLightEnable #右灯
uint8 doubleLightEnable #双闪
uint8 whistleEnable #喇叭
uint8 rgbLightEnable #RGB灯

float32 vehicleSpeed
uint8 bypassProcessing 

#Tractor
uint8 hookCmd   

#sweeper
uint8 sweepCmd
uint8 sprayCmd
uint8 unloadGarbage

