// Generated by gencpp from file ivlocmsg/ivmsglocpos.msg
// DO NOT EDIT!


#ifndef IVLOCMSG_MESSAGE_IVMSGLOCPOS_H
#define IVLOCMSG_MESSAGE_IVMSGLOCPOS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace ivlocmsg
{
template <class ContainerAllocator>
struct ivmsglocpos_
{
  typedef ivmsglocpos_<ContainerAllocator> Type;

  ivmsglocpos_()
    : header()
    , lon(0.0)
    , lat(0.0)
    , roll(0.0)
    , pitch(0.0)
    , heading(0.0)
    , xg(0.0)
    , yg(0.0)
    , zg(0.0)
    , angle(0.0)
    , hook_xg(0.0)
    , hook_yg(0.0)
    , hook_heading(0.0)
    , velocity(0.0)
    , velocity_sys(0.0)
    , yaw_rate(0.0)
    , localization_mode(0)
    , localization_status(0)
    , gps_status(0)
    , initial_gbias()
    , integral_lidar()
    , integral_gnss()
    , integral_odom()
    , abias()
    , gbias()
    , states()
    , offset()
    , odom_reckoning_time(0.0)
    , trans_stable_theshold(0.0)
    , trans_probability(0.0)
    , satenum(0)
    , height(0.0)
    , utctime(0.0)
    , base_length(0.0)
    , is_heading_valid(0)  {
      initial_gbias.assign(0);

      integral_lidar.assign(0);

      integral_gnss.assign(0);

      integral_odom.assign(0);

      abias.assign(0);

      gbias.assign(0);

      states.assign(0);

      offset.assign(0);
  }
  ivmsglocpos_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , lon(0.0)
    , lat(0.0)
    , roll(0.0)
    , pitch(0.0)
    , heading(0.0)
    , xg(0.0)
    , yg(0.0)
    , zg(0.0)
    , angle(0.0)
    , hook_xg(0.0)
    , hook_yg(0.0)
    , hook_heading(0.0)
    , velocity(0.0)
    , velocity_sys(0.0)
    , yaw_rate(0.0)
    , localization_mode(0)
    , localization_status(0)
    , gps_status(0)
    , initial_gbias()
    , integral_lidar()
    , integral_gnss()
    , integral_odom()
    , abias()
    , gbias()
    , states()
    , offset()
    , odom_reckoning_time(0.0)
    , trans_stable_theshold(0.0)
    , trans_probability(0.0)
    , satenum(0)
    , height(0.0)
    , utctime(0.0)
    , base_length(0.0)
    , is_heading_valid(0)  {
  (void)_alloc;
      initial_gbias.assign(0);

      integral_lidar.assign(0);

      integral_gnss.assign(0);

      integral_odom.assign(0);

      abias.assign(0);

      gbias.assign(0);

      states.assign(0);

      offset.assign(0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _lon_type;
  _lon_type lon;

   typedef double _lat_type;
  _lat_type lat;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;

   typedef double _heading_type;
  _heading_type heading;

   typedef double _xg_type;
  _xg_type xg;

   typedef double _yg_type;
  _yg_type yg;

   typedef double _zg_type;
  _zg_type zg;

   typedef double _angle_type;
  _angle_type angle;

   typedef double _hook_xg_type;
  _hook_xg_type hook_xg;

   typedef double _hook_yg_type;
  _hook_yg_type hook_yg;

   typedef double _hook_heading_type;
  _hook_heading_type hook_heading;

   typedef double _velocity_type;
  _velocity_type velocity;

   typedef double _velocity_sys_type;
  _velocity_sys_type velocity_sys;

   typedef double _yaw_rate_type;
  _yaw_rate_type yaw_rate;

   typedef int32_t _localization_mode_type;
  _localization_mode_type localization_mode;

   typedef int32_t _localization_status_type;
  _localization_status_type localization_status;

   typedef uint8_t _gps_status_type;
  _gps_status_type gps_status;

   typedef boost::array<int32_t, 3>  _initial_gbias_type;
  _initial_gbias_type initial_gbias;

   typedef boost::array<int32_t, 4>  _integral_lidar_type;
  _integral_lidar_type integral_lidar;

   typedef boost::array<int32_t, 4>  _integral_gnss_type;
  _integral_gnss_type integral_gnss;

   typedef boost::array<int32_t, 3>  _integral_odom_type;
  _integral_odom_type integral_odom;

   typedef boost::array<int32_t, 3>  _abias_type;
  _abias_type abias;

   typedef boost::array<int32_t, 3>  _gbias_type;
  _gbias_type gbias;

   typedef boost::array<int32_t, 3>  _states_type;
  _states_type states;

   typedef boost::array<int32_t, 4>  _offset_type;
  _offset_type offset;

   typedef double _odom_reckoning_time_type;
  _odom_reckoning_time_type odom_reckoning_time;

   typedef double _trans_stable_theshold_type;
  _trans_stable_theshold_type trans_stable_theshold;

   typedef double _trans_probability_type;
  _trans_probability_type trans_probability;

   typedef uint8_t _satenum_type;
  _satenum_type satenum;

   typedef double _height_type;
  _height_type height;

   typedef double _utctime_type;
  _utctime_type utctime;

   typedef double _base_length_type;
  _base_length_type base_length;

   typedef uint8_t _is_heading_valid_type;
  _is_heading_valid_type is_heading_valid;





  typedef boost::shared_ptr< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> const> ConstPtr;

}; // struct ivmsglocpos_

typedef ::ivlocmsg::ivmsglocpos_<std::allocator<void> > ivmsglocpos;

typedef boost::shared_ptr< ::ivlocmsg::ivmsglocpos > ivmsglocposPtr;
typedef boost::shared_ptr< ::ivlocmsg::ivmsglocpos const> ivmsglocposConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ivlocmsg::ivmsglocpos_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ivlocmsg::ivmsglocpos_<ContainerAllocator1> & lhs, const ::ivlocmsg::ivmsglocpos_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.lon == rhs.lon &&
    lhs.lat == rhs.lat &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch &&
    lhs.heading == rhs.heading &&
    lhs.xg == rhs.xg &&
    lhs.yg == rhs.yg &&
    lhs.zg == rhs.zg &&
    lhs.angle == rhs.angle &&
    lhs.hook_xg == rhs.hook_xg &&
    lhs.hook_yg == rhs.hook_yg &&
    lhs.hook_heading == rhs.hook_heading &&
    lhs.velocity == rhs.velocity &&
    lhs.velocity_sys == rhs.velocity_sys &&
    lhs.yaw_rate == rhs.yaw_rate &&
    lhs.localization_mode == rhs.localization_mode &&
    lhs.localization_status == rhs.localization_status &&
    lhs.gps_status == rhs.gps_status &&
    lhs.initial_gbias == rhs.initial_gbias &&
    lhs.integral_lidar == rhs.integral_lidar &&
    lhs.integral_gnss == rhs.integral_gnss &&
    lhs.integral_odom == rhs.integral_odom &&
    lhs.abias == rhs.abias &&
    lhs.gbias == rhs.gbias &&
    lhs.states == rhs.states &&
    lhs.offset == rhs.offset &&
    lhs.odom_reckoning_time == rhs.odom_reckoning_time &&
    lhs.trans_stable_theshold == rhs.trans_stable_theshold &&
    lhs.trans_probability == rhs.trans_probability &&
    lhs.satenum == rhs.satenum &&
    lhs.height == rhs.height &&
    lhs.utctime == rhs.utctime &&
    lhs.base_length == rhs.base_length &&
    lhs.is_heading_valid == rhs.is_heading_valid;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ivlocmsg::ivmsglocpos_<ContainerAllocator1> & lhs, const ::ivlocmsg::ivmsglocpos_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ivlocmsg

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0ccfe4354ecd3498e7410a145bdffba7";
  }

  static const char* value(const ::ivlocmsg::ivmsglocpos_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0ccfe4354ecd3498ULL;
  static const uint64_t static_value2 = 0xe7410a145bdffba7ULL;
};

template<class ContainerAllocator>
struct DataType< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ivlocmsg/ivmsglocpos";
  }

  static const char* value(const ::ivlocmsg::ivmsglocpos_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n"
"float64 lon\n"
"float64 lat\n"
"float64 roll\n"
"float64 pitch\n"
"float64 heading\n"
"float64 xg\n"
"float64 yg\n"
"float64 zg\n"
"float64 angle\n"
"float64 hook_xg\n"
"float64 hook_yg\n"
"float64 hook_heading\n"
"float64 velocity\n"
"float64 velocity_sys\n"
"float64 yaw_rate\n"
"int32 localization_mode\n"
"int32 localization_status\n"
"uint8 gps_status\n"
"int32[3] initial_gbias\n"
"int32[4] integral_lidar\n"
"int32[4] integral_gnss\n"
"int32[3] integral_odom\n"
"int32[3] abias\n"
"int32[3] gbias\n"
"int32[3] states\n"
"int32[4] offset\n"
"float64 odom_reckoning_time\n"
"float64 trans_stable_theshold\n"
"float64 trans_probability\n"
"uint8 satenum\n"
"float64 height\n"
"float64 utctime\n"
"float64 base_length\n"
"uint8 is_heading_valid\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::ivlocmsg::ivmsglocpos_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.lon);
      stream.next(m.lat);
      stream.next(m.roll);
      stream.next(m.pitch);
      stream.next(m.heading);
      stream.next(m.xg);
      stream.next(m.yg);
      stream.next(m.zg);
      stream.next(m.angle);
      stream.next(m.hook_xg);
      stream.next(m.hook_yg);
      stream.next(m.hook_heading);
      stream.next(m.velocity);
      stream.next(m.velocity_sys);
      stream.next(m.yaw_rate);
      stream.next(m.localization_mode);
      stream.next(m.localization_status);
      stream.next(m.gps_status);
      stream.next(m.initial_gbias);
      stream.next(m.integral_lidar);
      stream.next(m.integral_gnss);
      stream.next(m.integral_odom);
      stream.next(m.abias);
      stream.next(m.gbias);
      stream.next(m.states);
      stream.next(m.offset);
      stream.next(m.odom_reckoning_time);
      stream.next(m.trans_stable_theshold);
      stream.next(m.trans_probability);
      stream.next(m.satenum);
      stream.next(m.height);
      stream.next(m.utctime);
      stream.next(m.base_length);
      stream.next(m.is_heading_valid);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ivmsglocpos_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ivlocmsg::ivmsglocpos_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ivlocmsg::ivmsglocpos_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "lon: ";
    Printer<double>::stream(s, indent + "  ", v.lon);
    s << indent << "lat: ";
    Printer<double>::stream(s, indent + "  ", v.lat);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "xg: ";
    Printer<double>::stream(s, indent + "  ", v.xg);
    s << indent << "yg: ";
    Printer<double>::stream(s, indent + "  ", v.yg);
    s << indent << "zg: ";
    Printer<double>::stream(s, indent + "  ", v.zg);
    s << indent << "angle: ";
    Printer<double>::stream(s, indent + "  ", v.angle);
    s << indent << "hook_xg: ";
    Printer<double>::stream(s, indent + "  ", v.hook_xg);
    s << indent << "hook_yg: ";
    Printer<double>::stream(s, indent + "  ", v.hook_yg);
    s << indent << "hook_heading: ";
    Printer<double>::stream(s, indent + "  ", v.hook_heading);
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
    s << indent << "velocity_sys: ";
    Printer<double>::stream(s, indent + "  ", v.velocity_sys);
    s << indent << "yaw_rate: ";
    Printer<double>::stream(s, indent + "  ", v.yaw_rate);
    s << indent << "localization_mode: ";
    Printer<int32_t>::stream(s, indent + "  ", v.localization_mode);
    s << indent << "localization_status: ";
    Printer<int32_t>::stream(s, indent + "  ", v.localization_status);
    s << indent << "gps_status: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.gps_status);
    s << indent << "initial_gbias[]" << std::endl;
    for (size_t i = 0; i < v.initial_gbias.size(); ++i)
    {
      s << indent << "  initial_gbias[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.initial_gbias[i]);
    }
    s << indent << "integral_lidar[]" << std::endl;
    for (size_t i = 0; i < v.integral_lidar.size(); ++i)
    {
      s << indent << "  integral_lidar[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.integral_lidar[i]);
    }
    s << indent << "integral_gnss[]" << std::endl;
    for (size_t i = 0; i < v.integral_gnss.size(); ++i)
    {
      s << indent << "  integral_gnss[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.integral_gnss[i]);
    }
    s << indent << "integral_odom[]" << std::endl;
    for (size_t i = 0; i < v.integral_odom.size(); ++i)
    {
      s << indent << "  integral_odom[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.integral_odom[i]);
    }
    s << indent << "abias[]" << std::endl;
    for (size_t i = 0; i < v.abias.size(); ++i)
    {
      s << indent << "  abias[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.abias[i]);
    }
    s << indent << "gbias[]" << std::endl;
    for (size_t i = 0; i < v.gbias.size(); ++i)
    {
      s << indent << "  gbias[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.gbias[i]);
    }
    s << indent << "states[]" << std::endl;
    for (size_t i = 0; i < v.states.size(); ++i)
    {
      s << indent << "  states[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.states[i]);
    }
    s << indent << "offset[]" << std::endl;
    for (size_t i = 0; i < v.offset.size(); ++i)
    {
      s << indent << "  offset[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.offset[i]);
    }
    s << indent << "odom_reckoning_time: ";
    Printer<double>::stream(s, indent + "  ", v.odom_reckoning_time);
    s << indent << "trans_stable_theshold: ";
    Printer<double>::stream(s, indent + "  ", v.trans_stable_theshold);
    s << indent << "trans_probability: ";
    Printer<double>::stream(s, indent + "  ", v.trans_probability);
    s << indent << "satenum: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.satenum);
    s << indent << "height: ";
    Printer<double>::stream(s, indent + "  ", v.height);
    s << indent << "utctime: ";
    Printer<double>::stream(s, indent + "  ", v.utctime);
    s << indent << "base_length: ";
    Printer<double>::stream(s, indent + "  ", v.base_length);
    s << indent << "is_heading_valid: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_heading_valid);
  }
};

} // namespace message_operations
} // namespace ros

#endif // IVLOCMSG_MESSAGE_IVMSGLOCPOS_H
